---
markdown: kramdown
plugins:
  - jekyll-redirect-from
url: https://git.soma.salesforce.com
baseurl: /pages/API-Stewardship/sf.aip.dev
github:
  repository_url: https://git.soma.salesforce.com/API-Stewardship/sf.aip.dev
include:
  - CONTRIBUTING.md
  - README.md
defaults:
  - scope:
      path: aip
    values:
      permalink: none
  - scope:
      path: CONTRIBUTING.md
    values:
      exclude_from_search: true
      permalink: /contributing
  - scope:
      path: index.md
    values:
      exclude_from_search: true
      permalink: /
tipue_search:
  include:
    pages: true
